[tox]
envlist = py{310,314}, coverage, docs, style

[testenv]
setenv = COVERAGE_FILE={toxworkdir}/.coverage.{envname}
usedevelop = True
deps = -rrequirements.txt
       -rtests/requirements.txt
commands = pytest {posargs:-vv --cov=src/  --cov=tests/  --cov-report= tests/}

[testenv:coverage]
setenv = COVERAGE_FILE={toxworkdir}/.coverage
skip_install = True
deps = coverage
commands = coverage combine
           coverage report -m
           coverage xml
           coverage html

[testenv:docs]
skip_install = True
deps = check-manifest
       readme-renderer
commands = check-manifest
           python setup.py check --strict --restructuredtext

[testenv:style]
skip_install = True
deps = ruff
commands = ruff check
           ruff format --diff

[testenv:reformat]
skip_install = True
deps = ruff
commands = ruff check --fix
           ruff format


[check-manifest]
ignore = tests/**
         docs/*
         requirements.txt
         tox.ini

[coverage:xml]
output = .tox/test-reports/coverage.xml
[coverage:html]
directory = .tox/test-reports/htmlcov
