[tox]
envlist = py{39,310,314}, coverage, style, typecheck

[testenv]
setenv = COVERAGE_FILE={toxworkdir}/.coverage.{envname}
usedevelop = True
deps = -rtests/requirements.txt
commands = pytest {posargs:-vv --cov=src tests}

[testenv:coverage]
setenv = COVERAGE_FILE={toxworkdir}/.coverage
skip_install = True
deps = coverage
commands = coverage combine
           coverage report -m
           coverage xml
           coverage html

[testenv:style]
skip_install = True
deps = ruff
commands = ruff check
           ruff format --diff

[testenv:typecheck]
usedevelop = True
deps = pyright
commands = pyright

[testenv:reformat]
skip_install = True
deps = ruff
commands = ruff check --fix
           ruff format


[coverage:xml]
output = .tox/test-reports/coverage.xml
[coverage:html]
directory = .tox/test-reports/htmlcov
